### ISSUE TITLE
Expiration time for UNL to be user configurable

### ISSUE THREAD

**Issue by alloynetworks** [antIggl/xrpl-unl-manager#9]
https://github.com/antIggl/xrpl-unl-manager/blob/b9667d3d921ba1b05a5f794e01a679e2a7e48a85/utils.py#L192 is hard coded to 1 year from moment of running. This should be configurable as an argument.

**Comment by antIggl** [comment]
Nice point @alloynetworks. 
My initial goal was to create a tool to generate custom UNLs for our testnet, in order to test various connectivity scenarios between validators. Anyway, not an issue, I have already done it.

Expiration date added as argument in all createUNL() function. Defaults to 1 year later.
Additionally, *encodeUNL.py*  script can be used to set both expiration date and sequence/version of the UNL.
I am closing this issue.
